#!/bin/bash

## #ddev-generated
## ## Description: Build sitediff gem.
## Usage: ddev build-sitediff

cd /sitediff

gem install thor rspec --no-document

apt-get install -y liblzma-dev
gem install nokogiri -- --use-system-libraries --with-xml2-include=/usr/include/libxml2 --with-xml2-lib=/usr/lib/

# Build as a gem
gem build sitediff.gemspec && gem install sitediff --no-document

# Build locally
bundle install
